#!/usr/bin/env bash
# Re-run prebuild.sh to refresh src/content/docs/local/ from the sources
# listed in local-trees.conf. Designed to be called from post-commit
# hooks in the source repos.
#
# - flock prevents concurrent prebuilds (commits arriving in quick
#   succession would otherwise race on the same dest dirs).
# - Output goes to .omc/local-trees-refresh.log so commits stay quiet.
# - Always exits 0; a refresh failure must never block a commit.
set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$HERE/.omc"
LOG_FILE="$LOG_DIR/local-trees-refresh.log"
LOCK_FILE="$LOG_DIR/local-trees-refresh.lock"

mkdir -p "$LOG_DIR"

{
  echo
  echo "=== $(date -Iseconds)  refresh triggered by ${1:-unknown} ==="
  flock -n 9 || { echo "another refresh is running; skipping"; exit 0; }
  bash "$HERE/prebuild.sh" 2>&1
  rc=$?
  echo "=== prebuild exit=$rc ==="
  if [[ $rc -eq 0 ]]; then
    # Rewrite local-trees-marker.mjs with a fresh ISO timestamp. A static
    # import in astro.config.mjs pulls this file into vite's config-watch
    # graph, so a content change forces vite to re-evaluate the config —
    # which re-runs scanLocalSidebar() and picks up new
    # src/content/docs/local/<dir>/ entries. mtime-only `touch` does NOT
    # work (vite ignores no-op writes). No-op when no dev server runs.
    printf '%s\n' \
      '// Auto-generated by scripts/refresh-local-trees.sh — do not hand-edit.' \
      "export const LAST_REFRESH = '$(date -Iseconds)';" \
      > "$HERE/local-trees-marker.mjs"
    echo "=== $(date -Iseconds)  bumped local-trees-marker.mjs (dev-server sidebar reload) ==="

    echo "=== $(date -Iseconds)  astro build ==="
    # post-commit hooks spawn this script with a minimal PATH; prepend
    # the user-local bin where node/npm live.
    (cd "$HERE" && PATH="/home/hgryoo/.local/bin:$PATH" npm run build) 2>&1
    brc=$?
    echo "=== $(date -Iseconds)  build exit=$brc ==="
  else
    echo "=== skip build (prebuild failed) ==="
  fi
} 9>"$LOCK_FILE" >>"$LOG_FILE" 2>&1

exit 0
